In [1]:
from mxnet import nd

In [2]:
x = nd.arange(12)
x


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)>

In [7]:
x.shape
x.size

12

In [10]:
X = x.reshape((3,4))
X


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [11]:
nd.zeros((2,3,4))


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
<NDArray 2x3x4 @cpu(0)>

In [13]:
nd.ones((3,4))


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>

In [14]:
nd.random.normal(0,1,shape=(3,4))


[[ 1.1630785   0.4838046   0.29956347  0.15302546]
 [-1.1688148   1.5580711  -0.5459446  -2.3556297 ]
 [ 0.5414402   2.6785066   1.2546345  -0.54877394]]
<NDArray 3x4 @cpu(0)>

In [16]:
Y = nd.array([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
X+Y


[[ 2.  2.  6.  6.]
 [ 5.  7.  9. 11.]
 [12. 12. 12. 12.]]
<NDArray 3x4 @cpu(0)>

In [17]:
X*Y


[[ 0.  1.  8.  9.]
 [ 4. 10. 18. 28.]
 [32. 27. 20. 11.]]
<NDArray 3x4 @cpu(0)>

In [18]:
X/Y


[[ 0.    1.    0.5   1.  ]
 [ 4.    2.5   2.    1.75]
 [ 2.    3.    5.   11.  ]]
<NDArray 3x4 @cpu(0)>

In [19]:
Y.exp()


[[ 7.389056   2.7182817 54.59815   20.085537 ]
 [ 2.7182817  7.389056  20.085537  54.59815  ]
 [54.59815   20.085537   7.389056   2.7182817]]
<NDArray 3x4 @cpu(0)>

In [20]:
nd.dot(X,Y.T)      #T 转置  dot 矩阵乘法


[[ 18.  20.  10.]
 [ 58.  60.  50.]
 [ 98. 100.  90.]]
<NDArray 3x3 @cpu(0)>

In [21]:
nd.concat(X,Y,dim = 0),nd.concat(X,Y,dim = 1)     #连结 在行与列维度上进行连接

(
 [[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]
  [ 2.  1.  4.  3.]
  [ 1.  2.  3.  4.]
  [ 4.  3.  2.  1.]]
 <NDArray 6x4 @cpu(0)>, 
 [[ 0.  1.  2.  3.  2.  1.  4.  3.]
  [ 4.  5.  6.  7.  1.  2.  3.  4.]
  [ 8.  9. 10. 11.  4.  3.  2.  1.]]
 <NDArray 3x8 @cpu(0)>)

In [22]:
 X == Y


[[0. 1. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<NDArray 3x4 @cpu(0)>

In [24]:
X.sum()     #所有元素球和


[66.]
<NDArray 1 @cpu(0)>

In [26]:
X.norm().asscalar()

22.494442

In [28]:
A = nd.arange(3).reshape((3,1))
B = nd.arange(2).reshape((1,2))
A,B

(
 [[0.]
  [1.]
  [2.]]
 <NDArray 3x1 @cpu(0)>, 
 [[0. 1.]]
 <NDArray 1x2 @cpu(0)>)

In [29]:
A+B


[[0. 1.]
 [1. 2.]
 [2. 3.]]
<NDArray 3x2 @cpu(0)>

In [30]:
X[1:3]    #截取行


[[ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 2x4 @cpu(0)>

In [33]:
X[1,2] = 9
X


[[ 0.  1.  2.  3.]
 [ 4.  5.  9.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [34]:
X[1:2, :] = 12
X


[[ 0.  1.  2.  3.]
 [12. 12. 12. 12.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [36]:
beforeId = id(Y)      #id指向内存
Y = Y+X
id(Y) == beforeId

False

In [37]:
Z = Y.zeros_like()
before = id(Z)
Z[:] = X + Y
id(Z) == before       #通过索引存储保证内存指向相同

True

In [38]:
nd.elemwise_add(X, Y, out=Z)
id(Z) == before

True

In [39]:
before = id(X)
X += Y
id(X) == before

True

In [41]:
#NDArray与NP相互转换
import numpy as np

P = np.ones((2,3))
D = nd.array(P)
D


[[1. 1. 1.]
 [1. 1. 1.]]
<NDArray 2x3 @cpu(0)>

In [42]:
D.asnumpy()

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [2]:
#自动求梯度

from mxnet import autograd,nd

x = nd.arange(4).reshape((4,1))

x.attach_grad()        #申请存储梯度要的内存
with autograd.record():
    y = 2*nd.dot(x.T,x)

y.backward()

assert(x.grad - 4*x).norm().asscalar() == 0
x.grad


[[ 0.]
 [ 4.]
 [ 8.]
 [12.]]
<NDArray 4x1 @cpu(0)>

In [3]:
print(autograd.is_training())
with autograd.record():
    print(autograd.is_training())


False
True


In [5]:
#对控制流求梯度
def f(a):
    b = a*2
    while b.norm().asscalar() < 1000:
        b = b*2
    if b.sum().asscalar()>0:
        c = b
    else:
        c = 100*b
    return c

In [6]:
a = nd.random.normal(shape=1)
a.attach_grad()
with autograd.record():
    c = f(a)
c.backward()
a.grad == c/a


[1.]
<NDArray 1 @cpu(0)>

In [7]:
print (dir(nd.random))      #查询对象成员与属性

['NDArray', '_Null', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '_internal', '_random_helper', 'current_context', 'exponential', 'exponential_like', 'gamma', 'gamma_like', 'generalized_negative_binomial', 'generalized_negative_binomial_like', 'multinomial', 'negative_binomial', 'negative_binomial_like', 'normal', 'normal_like', 'numeric_types', 'poisson', 'poisson_like', 'randint', 'randn', 'shuffle', 'uniform', 'uniform_like']


In [8]:
help(nd.ones_like)

Help on function ones_like:

ones_like(data=None, out=None, name=None, **kwargs)
    Return an array of ones with the same shape and type
    as the input array.
    
    Examples::
    
      x = [[ 0.,  0.,  0.],
           [ 0.,  0.,  0.]]
    
      ones_like(x) = [[ 1.,  1.,  1.],
                      [ 1.,  1.,  1.]]
    
    
    
    Parameters
    ----------
    data : NDArray
        The input
    
    out : NDArray, optional
        The output NDArray to hold the result.
    
    Returns
    -------
    out : NDArray or list of NDArrays
        The output of this function.



In [9]:
x = nd.array([[0,0,0],[2,2,2]])
y = x.ones_like()
y


[[1. 1. 1.]
 [1. 1. 1.]]
<NDArray 2x3 @cpu(0)>